kind: pipeline
type: docker
name: latestbuild

steps:
  - name: build
    image: golang
    commands:
      - go test ./...
      - CGO_ENABLED=0 go build
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: gitea_user
      password:
        from_secret: gitea_password
      repo: git.neer.family/jneer/DbotRemastered
      registry: git.neer.family
      tags: latest
      force_tag: true
      purge: true

trigger:
  branch:
    - main
  event:
    - push
